# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-26 04:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[(b'B', b'Bread'), (b'D', b'Diary'), (b'F', b'Fruits'), (b'S', b'Seasonings'), (b'V', b'Vegetables')], max_length=2)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=15)),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'usersCarts',
            },
        ),
    ]
