# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-27 02:53
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, default='aaaaaaaaaaaaaaaaaaaaaa', editable=False),
            preserve_default=False,
        ),
    ]
