# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-26 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 26, 0, 17, 20, 521532, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 26, 0, 17, 35, 990713, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
