# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-27 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(blank=True, max_length=63, null=True)),
                ('level_number', models.CharField(blank=True, max_length=63, null=True)),
                ('street_number', models.CharField(blank=True, max_length=63, null=True)),
                ('street_name', models.CharField(blank=True, max_length=63, null=True)),
                ('suburb', models.CharField(blank=True, max_length=63, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('state', models.CharField(blank=True, choices=[(b'N', b'New South Wales'), (b'V', b'Victoria'), (b'Q', b'Queensland'), (b'S', b'South Australia'), (b'N', b'Northern Territory'), (b'W', b'Western Australia'), (b'T', b'Tasmania')], max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
