# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, choices=[(b'N', b'New South Wales'), (b'V', b'Victoria'), (b'C', b'Australian Capital Territory'), (b'Q', b'Queensland'), (b'S', b'South Australia'), (b'T', b'Northern Territory'), (b'W', b'Western Australia'), (b'A', b'Tasmania')], max_length=4, null=True),
        ),
    ]
